### ISSUE TITLE
unalias and edit throw unreasonable errors

### ISSUE THREAD

**Issue by jacktose** [Homebrew/homebrew-aliases#12]
`unalias` always says the alias doesn't exist.  
`alias --edit` always says the alias already exists (which is true, but shouldn't be an error).

```
$ brew alias
brew alias overwrite='info %'
brew alias i='install'
$ brew unalias overwrite
Error: 'brew overwrite' is not aliased to anything.
$ brew alias --edit overwrite
Error: 'brew overwrite' already exists. Sorry.
$ brew unalias i
Error: 'brew i' is not aliased to anything.
```

**Comment by bfontaine** [comment]
Could you please post the output of the following commands?
1. `ls -l ~/.brew-aliases/`
2. `ls -l $(brew --prefix)/bin/brew-overwrite`
3. `ls -l $(brew --prefix)/bin/brew-i`

**Comment by bfontaine** [comment]
I can’t reproduce, so I’m closing this. Please reopen if the issue persists, including the output of the commands from my previous comment.
