### ISSUE TITLE
Allow commands for homebrew-cask aliases starting with `cask`

### ISSUE THREAD

**Issue by singularitti** [Homebrew/homebrew-aliases#13]
Great to see that you have such a useful tool!

I am thinking about why not have a tool for homebrew-cask command line? Which does the same thing as `homebrew-aliases` but the command starts with `cask`. How do you like the idea?

**Comment by singularitti** [comment]
For example,
```shell
# brew cask update --> cask up
cask alias up='update'
```

**Comment by bfontaine** [comment]
`homebrew-aliases` works by using Homebrew’s support for custom commands. When one types `brew foo`, where `foo` is not an existing command, Homebrew checks if there’s a `brew-foo` executable somewhere in your `$PATH` and uses that (it’s a bit more complex but that’s the idea).

`cask` is already a `brew` command so we can’t use this trick. All we could do is have `cask-` aliases such as `brew cask-up` → `brew cask upgrade` but that doesn’t save you a lot of characters.
We can’t distribute executables from a tap, so a standalone `cask` command is not possible; it would also conflict with Emacs’ [`cask`](https://cask.readthedocs.io/en/latest/) project management tool.

**Comment by singularitti** [comment]
I see, thank you.
