### ISSUE TITLE
Save in XDG_CONFIG_HOME

### ISSUE THREAD

**Issue by texastoland** [Homebrew/homebrew-aliases#23]
I understand the backwards compatibility issue. It'd be nice to at least be able to configure the directory. Generally I'd expect it in `.config/brew-aliases`.

**Comment by bfontaine** [comment]
For backward compatibility we could do something like:

```
if exists("~/.brew-aliases") -> use it
if is_set("$XDG_CONFIG_HOME") -> use its value
otherwise -> use "~/.brew-aliases"
```

Do you want to try a pull-request? Right now the base directory is defined here: https://github.com/Homebrew/homebrew-aliases/blob/2c61f551a63aa97c0767c74856c6ae19c67a92e0/lib/aliases.rb#L5

**Comment by texastoland** [comment]
I'll try now!
