### ISSUE TITLE
Aliases are not saved into XDG_CONFIG_HOME

### ISSUE THREAD

**Issue by WavinFlag** [Homebrew/homebrew-aliases#29]
...as line 9 always fails.
https://github.com/Homebrew/homebrew-aliases/blob/da6f87a7722e329331b978ba3cdb515b872af944/lib/aliases.rb#L8-L12

Changing it to
```ruby
    Pathname.new("~/.config/brew-aliases").expand_path
```
should fix it, but then the latter condition (`"~/.brew-aliases"`) is never reached.

**Comment by bfontaine** [comment]
Sorry for the delay, it should be fixed now.
