### ISSUE TITLE
Aliases aren't found

### ISSUE THREAD

**Issue by timcleaver** [Homebrew/homebrew-aliases#32]
I have a fresh install of homebrew and homebrew-aliases on macos catalina and none of the aliases I created take effect.

`$ brew --version`
> Homebrew 3.0.5-62-gacfe9d2
> Homebrew/homebrew-core (git revision ee7e17270e; last commit 2021-03-15)
> Homebrew/homebrew-cask (git revision 86545bc466; last commit 2021-03-15)

`$ brew tap --debug --verbose`
> adoptopenjdk/openjdk
> aws/tap
> chrokh/tap
> colindean/fonts-nonfree
> homebrew/aliases
> homebrew/cask
> homebrew/cask-fonts
> homebrew/cask-versions
> homebrew/command-not-found
> homebrew/core
> jmespath/jmespath
> minio/stable
> paulfitz/data
> rbenv/tap
> saulpw/vd
> srkomodo/tap
> universal-ctags/universal-ctags

`$ brew alias`
> brew alias upg='upgrade'
> brew alias ci='cask install'
> brew alias i='install'
> brew alias old='outdated'
> brew alias cold='outdated --cask'
> brew alias cupg='cask upgrade'

`$  brew old`
> Error: Unknown command: old

`$ type -a brew`
> brew is /usr/local/bin/brew
> brew is /usr/local/bin/brew

`$ which brew`
> /usr/local/bin/brew

`$ echo $SHELL`
> /usr/local/bin/fish

`$ ls ~/.brew-aliases`
> ci  cold  cupg  i  old  upg

I am not sure what the issue is, but if there is any more information I can provide to help diagnose the issue please reach out.

**Comment by bfontaine** [comment]
Hello, does the following command show any output?

```bash
ls -l /usr/local/bin/brew-*
```

It should show one symlink per command; e.g. `/usr/local/bin/brew-old -> /home/you/.brew-aliases/old`.

**Comment by timcleaver** [comment]
No, it doesn't. 

`$ ls -l /usr/local/bin/brew-*`
> fish: No matches for wildcard '/usr/local/bin/brew-*'. See `help expand`.
> ls -l /usr/local/bin/brew-*

I will delete .brew-aliases (as I was using stow to save it and restore it). Looks like that isn't enough to correctly configure this and I will have to use `brew alias` from clean install to ensure everything is setup properly (unless there is another way to install aliases)?

Thank you for the prompt response. I figured it was user error since I couldn't find anybody else experiencing this.

**Comment by bfontaine** [comment]
Yes, right now there’s no way to create symlinks for aliases that already exist. You could do something like this (it’s Bash, but that gives you the idea):
```bash
for f in ~/.brew-aliases/* ; do
  ln -s $f "$(brew --prefix)/bin/brew-$(basename $f)"
done
```
