### ISSUE TITLE
Prefix "!" produces error

### ISSUE THREAD

**Issue by lylemoffitt** [Homebrew/homebrew-aliases#5]
Tried to create a simple alias with the "!" prefix, like so:
```shell
bash-4.4$ brew alias toast="!echo I like toast"
bash: !echo: event not found
```
The standard usage seems to work though.

**Comment by bfontaine** [comment]
This is caused by Bash interpreting `!` inside double quotes. The [README](https://github.com/Homebrew/homebrew-aliases#notes) says that "you may need quotes to prevent your shell from interpreting `!`"; we should maybe clarify that sentence.

You can use single quotes to prevent this:

```
$ brew alias toast='!echo I like toast'
$ brew toast
I like toast
```

**Comment by lylemoffitt** [comment]
Lol. Now that you mention that...  I really should have noticed in the README. I keep forgetting that different quotes have different meanings in the shell. 

I don't think you did anything wrong, but If I were going to change anything I'd change the first block to use the single quotes as well. Then I would provide a specific example where you use shell expansion, and only use the double-quotes there.

Alternatively, maybe choose a different sentinel that doesn't have a special meaning (like '%'). That way you can use shell expansion when you want to. I wanted to alias `brew alias git="! git -C $(brew --repo homebrew/core) "`,  and had a lot of trouble with this.

**Comment by bfontaine** [comment]
I used that because `git` itself does:

```
$ git alias toast '!echo I like toast'
$ git toast
I like toast
```

> I don't think you did anything wrong, but If I were going to change anything I'd change the first block to use the single quotes as well. Then I would provide a specific example where you use shell expansion, and only use the double-quotes there.

Good idea.

> Alternatively, maybe choose a different sentinel that doesn't have a special meaning (like '%').

We can’t remove the support for `!` but yeah we can add another character.
